### ISSUE TITLE
Compilation error on a Mac with UE 5.1

### ISSUE THREAD

**Issue by cdigiacinto** [irajsb/UE4_TitanUMG#1]
Hello, 

If I try to update the project from UE 5.0.3 to 5.1 I get the following error:
Too few arguments to function call, expected 4, have 3; did you mean 'FGenericApplicationMessageHandler::OnControllerAnalog'?

Do you plan to update the plugin for the new version of Unreal?

**Comment by irajsb** [comment]
Seems like UE5.1 API Changes.I will push an update soon .

**Comment by cdigiacinto** [comment]
Thank you very much for the quick reply. There are also other errors. Do you need the full error logs?

**Comment by irajsb** [comment]
nope I'm compiling it on my side

**Comment by irajsb** [comment]
https://github.com/irajsb/UE4_TitanUMG/tree/UE5
Fixed
