### ISSUE TITLE
Cant't build in unereal 5.3

### ISSUE THREAD

**Issue by ToufiqurTushar** [irajsb/UE4_TitanUMG#4]
Unreal 5.1, 5.2 has no error with this plugin but in 5.3 FSlateApplication::Get().OnControllerAnalog() requires 4 parameters.
value of FPlatformUserId, FInputDeviceId are missing in you plugin
Anyway, Thanks for your Excellent work

**Comment by irajsb** [comment]
Are you using UE5 branch ?
https://github.com/irajsb/UE4_TitanUMG/tree/UE5
